### ISSUE TITLE
orfm codon call for degenerative bases

### ISSUE THREAD

**Issue by caity-s** [wwood/OrfM#1]
Hello wwood,

Just to let you know, it looks as though OrfM has problems with degenerative codons, just had a run though of GraftM on a database of IMG genomes (full contigs) and it fell at this point: 
06/12/2015 12:40:49 PM INFO: Searching methanotroph_mock_FINAL.fna
Detected unexcepted codon: GYATCATAGGCCAGCCGCTGTCCAGATGCACCGGTTCATCTGCGTCAGACGACGATCTTCACCCGGTAACCCCCGCCGATCACCAGATACTCGGCCTCCCCGCGCAAAGGATGGCTCGGCAGCAGATCGTTGAAGAACAGGAGCTTCACGACCGGAACTTCGGTTTCGAGGATATAGGCACCGAACTGCCCCGCCTGCGTCCGGTCAGCGGAGAAAGAAACGATGTTGTTGAGACGCACGAGGATTTCCCGTCCGTTGCCGGCCCC
Must be the Y! Some IMG genomes have a number of other problematic sequences amongst their genomes, such as this treasure:
RYASMRMARCKYRRMKGMMSMMSAMGCARRWMYCSACGSYCARMYSYMSWTSSSMSKSWKCRCGMCRRAACMSMRYAWMAGCSSGACRMWYRSSMWCSMG

Thanks!

**Comment by wwood** [comment]
Thanks for the concise bug report, is easy to reproduce.

**Comment by wwood** [comment]
Fixed in 023c916 i.e. v0.4.1 and now on the ACE servers.
