### ISSUE TITLE
start codons

### ISSUE THREAD

**Issue by dtrujill0** [wwood/OrfM#12]
What are the default start codons for orfM? Is there a command/option for selecting certain start codons, i.e. only ORFs with ATG/AUG start codons?

**Comment by wwood** [comment]
Hi,

Unfortunately OrfM does not find start codons at all, instead looking for stretches free of stop codons. You might try orfipy which has that functionality
https://academic.oup.com/bioinformatics/article/37/18/3019/6134074?login=true

HTH, ben
