### ISSUE TITLE
the compressed file usage of orfm

### ISSUE THREAD

**Issue by jinxiangyabg** [wwood/OrfM#4]
Dear ben,I have another problem.I have read your paper,and find this software is capable in the compressed file .I have make some genome files  impressed.And using thin command as following:

orfm gene.fa.zip -t transcripts1.fa
and have nothing in the file  transcripts1.fa..Could you have this case?

**Comment by wwood** [comment]
Hi,

I'm guess we meant gzip compressed, not zip compressed. However, you can use unix pipes to achieve the same result, like so:

```
$ unzip -p /tmp/a.zip |orfm
```

Note though that a zip file can contain multiple files, and the above command will concatenate them all before piping them to OrfM, when you may in fact want ORFs called separately on each file - I'm not sure.

OK?

**Comment by jinxiangyabg** [comment]
I am very sorry to  reply so late.I have make several files into a file,and use the one file to implement
orfm!! Thank you very much for your patient guide!!

**Comment by wwood** [comment]
not a late reply at all. Let me know if there is anything else.
