### ISSUE TITLE
symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by rasmusagren** [wwood/OrfM#5]
Hi,

I'm trying to compile from source code on OSX, but I get the following error. Could you please point me in the right direction? I think it has to do with compiler flags, but I'm a bit lost in the whole autotools thing :)

```
gcc  -O2 -Wall -D ORFM_VERSION=\"0.5.3\" -Iext  -lz -o orfm src/orfm.o ext/ac.o  -lz
Undefined symbols for architecture x86_64:
  "_print_sequence", referenced from:
      _process_sequence_file in orfm.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Best regards,
Rasmus

**Comment by wwood** [comment]
Hi,

Thanks for your interest in OrfM, and for trying to package it for conda. I was able to reproduce this but then my wife woke up and wanted her laptop back. I think this might be a clang thing specifically, because `_print_sequence` is a function in orfm itself (specifically src/orfm.c), and orfm has no header files. Any idea how to fix this? I don't know much about clang.

Actually, I was also able to get the same errors with Guix on linux:
```
ben@u ~/git/OrfM$ guix environment --container orfm --ad-hoc automake libtool autoconf coreutils clang
ben@u ~/git/OrfM [env]# make clean
test -z "orfm" || rm -f orfm
rm -f *.o
rm -f ext/*.o
rm -f src/*.o
ben@u ~/git/OrfM [env]# ./configure
(snip)
ben@u ~/git/OrfM [env]# depbase=`echo src/orfm.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
<1 -DHAVE_MEMSET=1 -I.     -O2 -Wall -D ORFM_VERSION=\"0.5.3\" -Iext -MT src/orfm.o -MD -MP -MF $depbase.Tpo -c -o src/orfm.o src/orfm.c &&\
> mv -f $depbase.Tpo $depbase.Po
ben@u ~/git/OrfM [env]# depbase=`echo ext/ac.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
<ALLOC=1 -DHAVE_MEMSET=1 -I.     -O2 -Wall -D ORFM_VERSION=\"0.5.3\" -Iext -MT ext/ac.o -MD -MP -MF $depbase.Tpo -c -o ext/ac.o ext/ac.c &&\
> mv -f $depbase.Tpo $depbase.Po
ben@u ~/git/OrfM [env]# clang  -O2 -Wall -D ORFM_VERSION=\"0.5.3\" -Iext  -lz -o orfm src/orfm.o ext/ac.o  -lz 
src/orfm.o: In function `process_sequence_file':
src/orfm.c:(.text+0xbc7): undefined reference to `print_sequence'
src/orfm.c:(.text+0x1097): undefined reference to `print_sequence'
src/orfm.c:(.text+0x10e7): undefined reference to `print_sequence'
src/orfm.c:(.text+0x1130): undefined reference to `print_sequence'
src/orfm.c:(.text+0x120e): undefined reference to `print_sequence'
src/orfm.o:src/orfm.c:(.text+0x1252): more undefined references to `print_sequence' follow
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
```
I've run out of time to work on this right now, is there an obvious solution?
ta

**Comment by wwood** [comment]
Hi again, I think I fixed this, on Linux at least, with the help of http://stackoverflow.com/questions/12844729/linking-error-for-inline-functions#12845571

Would you mind seeing if that fixes it for you as well on OSX please? You can clone from https://github.com/wwood/OrfM/tree/clang-fix
Thanks.

**Comment by rasmusagren** [comment]
That seems to work. Thanks a lot!

**Comment by wwood** [comment]
Cool, thanks for the bug report.
