### ISSUE TITLE
Failed Make Check

### ISSUE THREAD

**Issue by okapick** [wwood/OrfM#7]
`make checkdepbase=`echo src/orfm.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DPACKAGE_NAME=\"orfm\" -DPACKAGE_TARNAME=\"orfm\" -DPACKAGE_VERSION=\"0.7.1\" -DPACKAGE_STRING=\"orfm\ 0.7.1\" -DPACKAGE_BUGREPORT=\"uq.edu.au\ after\ b.woodcroft\ ok\" -DPACKAGE_URL=\"\" -DPACKAGE=\"orfm\" -DVERSION=\"0.7.1\" -DHAVE_LIBZ=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE__BOOL=1 -DHAVE_STDLIB_H=1 -DHAVE_MALLOC=1 -DHAVE_STDLIB_H=1 -DHAVE_REALLOC=1 -DHAVE_MEMSET=1 -I.     -O2 -Wall -D ORFM_VERSION=\"0.7.1\" -Iext -MT src/orfm.o -MD -MP -MF $depbase.Tpo -c -o src/orfm.o src/orfm.c &&\
mv -f $depbase.Tpo $depbase.Po
src/orfm.c:8:10: fatal error: seqtk/kseq.h: No such file or directory
 #include <seqtk/kseq.h>
          ^~~~~~~~~~~~~~
compilation terminated.
Makefile:385: recipe for target 'src/orfm.o' failed
make: *** [src/orfm.o] Error 1
`

Good morning.

Here it the prompt about the mistake.
What can be it?

**Comment by wwood** [comment]
Hi,
`seqtk/kseq.h` is in a submodule, which means that's the zip file auto-generated by GitHub does not contain it. Did you download the source from https://github.com/wwood/OrfM/releases/download/v0.7.1/orfm-0.7.1.tar.gz ?

Thanks, ben

**Comment by okapick** [comment]
Thanks, This version is ok. Now it works.

I think you need to check the public release. Because i cloned the folder from the main page. 

Regards.

**Comment by wwood** [comment]
Hmm, not sure I follow what you mean. If you clone with `--recursive` as suggested in https://github.com/wwood/OrfM#contributing-to-orfm you should get the kseq.h file. I'm closing this now - let me know if there's anything I missed and I can reopen if needed.
